In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
type(arr)


numpy.ndarray

In [7]:
print(np.__version__)

2.3.5


In [8]:
import numpy as np
arr=np.array((4,5,6,7))
print(arr)

[4 5 6 7]


In [12]:
arr=np.array(12)
print(arr)
print(arr.ndim)
#0r
print(np.ndim(arr))

12
0
0


In [13]:
arr1=np.array([1,3,5,7,9])
print(arr1)
print(arr1.ndim)

[1 3 5 7 9]
1


In [14]:
arr2=np.array([[1,2,3],[9,8,7]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [9 8 7]]
2


In [15]:
arr3=np.array([[[2,4,6],[3,7,1]],[[5,6,7],[9,8,7]]])
print(arr3)
print(arr3.ndim)

[[[2 4 6]
  [3 7 1]]

 [[5 6 7]
  [9 8 7]]]
3


In [16]:
num=np.array([3,5,7,9], ndmin=3)
print(num)
print(num.ndim)

[[[3 5 7 9]]]
3


In [32]:
#indexing & slicing
#1D
num=np.array([1,3,5,7,9,4,2,7,9,8])
print(num[0])
print(num[1])
print(num[-2])
print(num[:3])
print(num[2:])
print(num[2:4])
print(num[-4:-1])
print(num[:5:2])
print(num[-8:-2:2])


1
3
9
[1 3 5]
[5 7 9 4 2 7 9 8]
[5 7]
[2 7 9]
[1 5 9]
[5 9 2]


In [33]:
#2D
num2=np.array([[1,2,3,4,5,6],[9,8,7,11,13,21]])
print(num2[0,1])
print(num2[1,2])
print(num2[1,-2])
print(num2[1,:3])
print(num2[0,2:])
print(num2[1,2:4])
print(num2[0:2,-4:-1])
print(num2[1,:5:2])



2
7
13
[9 8 7]
[3 4 5 6]
[ 7 11]
[[ 3  4  5]
 [ 7 11 13]]
[ 9  7 13]
